### ISSUE TITLE
Feature: Allow Ingress creation from within the chart

### ISSUE THREAD

**Issue by HaddadJoe** [neo4j/helm-charts#100]
**Is your feature request related to a problem? Please describe.**
We're deploying neo4j internally on gke using an internal load balancer. We want to be able to use an already existing ingress-controller to route traffic to our neo4j deployment. Right now, there's no possibility to do that directly from the helm chart. Happy to open PRs if this is something that would be accepted

**Describe the solution you'd like**
Solution would be to allow creation of ingresses for the services and specify basic configuration values for that ingress. Would probably require separate ingress for each service expose to have proper control. For example, deploy admin on a internal load balancer and the core app on an public facing one.

**Describe alternatives you've considered**
As alternatives, we've been externally creating ingresses to the services that we want to expose on our internal load balancer.

**Additional context**
Here are some other helm charts for reference that allow dynamic creation of ingresses from within the chart.
- [Grafana helm chart ingress](https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L197)
- [Jenkins helm chart ingress](https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml#L434)

**Comment by ojhughes** [comment]
Hi @HaddadJoe , the problem with Ingress is the Neo4j browser relies on both HTTP (7474) and Bolt (7687). I'm not sure if the browser would allow cross site communications with Bolt using a different ingress domain. This is something we would like to investigate in the future but I'm unsure how much work is required

**Comment by ojhughes** [comment]
I did some experimentation using HAProxy to proxy Bolt and HTTP traffic over the same port. We don't have immediate plans to add an HAProxy template to this chart but I will share my example so you can see that it is possible to configure an Ingress for the Neo4j chart. https://github.com/neo4j/helm-charts/commit/3cab78f1b308c21ceb834d43e1e902f9ff147b1e
