### ISSUE TITLE
[Bug]: Broken link on welcome page

### ISSUE THREAD

**Issue by nrouyer** [neo4j/helm-charts#106]
### Contact Details

nicolas.rouyer@neo4j.com

### What happened?

At the end of the landing page, the following link is broken:

https://neo4j.com/docs/operations-manual/current/kubernetes/

### Chart Name

Cluster

### Chart Version

4.4.3

### Environment

Issue seen on all the cloud providers (GCP , AWS , AKS)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harshitsinghvi22** [comment]
Hi @nrouyer 

the link seems to be loading fine 
https://neo4j.com/docs/operations-manual/current/kubernetes/

Can you please check and confirm back if this is the link you are referring to ?

Thanks,
Harshit

**Comment by nrouyer** [comment]
now it is!

Thanks, seemed to be temporary

Nicolas

Le jeu. 10 nov. 2022 à 11:45, Harshit Singhvi ***@***.***> a
écrit :
