### ISSUE TITLE
[Bug]: Unable to configure neo4j service type

### ISSUE THREAD

**Issue by hardincm2** [neo4j/helm-charts#120]
### Contact Details

cameron.hardin@spacex.com

### What happened?

It appears the Neo4j service resouce is created with `type: ClusterIP` hardcoded. Was this intentional? I assume this should be respecting the configuration values specified at time of helm install.

https://github.com/neo4j/helm-charts/blob/dev/neo4j/templates/neo4j-svc.yaml#L30
![CleanShot 2022-12-05 at 15 01 05](https://user-images.githubusercontent.com/9040162/205741863-b89edecc-bad4-46f3-9ffb-ca075468d79b.png)

I want to be able to create a `type: LoadBalancer` service for my database, which I used to be able to do in the previous helm charts for 4.3. Can only do this now by editing the k8s yaml after deploy manually.

Let me know if this should be updated, and I'd be happy to put up a PR.

Thanks,
Cam

### Chart Name

Standalone

### Chart Version

4.4.3

### Environment

Google Cloud Platform

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ojhughes** [comment]
Thanks for raising this. The team will discuss and get back to you

**Comment by afokin52** [comment]
in release 5.5.0 the error persisted

**Comment by harshitsinghvi22** [comment]
Hi @hardincm2 @afokin52 

The current helm charts creates a Loadbalancer type service automatically to access the Neo4j console and other Cluster IP services

The code mentioned in the description is rightly pointing to the ClusterIp type . We do not provide a way to modify the type of the mentioned service via the values.yaml

When you install a Neo4j community / enterprise edition, standalone or cluster, a LoadBalancer service gets created automatically to access the neo4j console.

Hope this helps.

Thanks,
Harshit

**Comment by harshitsinghvi22** [comment]
@hardincm2  @afokin52 is it fine if I close this issue ? If there's anything I am missing here. Please let me know

**Comment by harshitsinghvi22** [comment]
Closing this as no response received
