### ISSUE TITLE
Bring PR #118 into release 4.4

### ISSUE THREAD

**Issue by EvertonSA** [neo4j/helm-charts#122]
Hi colleagues,

A very good soul worked on this PR https://github.com/neo4j/helm-charts/pull/118 and I need this in the company I'm working on. I have not seen any move from dev branch into 4.4 branch after that got merged and I'm willing to contribute time to get this feature on 4.4 if human help is needed. 

How can I help, or, is there something I can do to help to get this feature on 4.4?

**Comment by EvertonSA** [comment]
hi @harshitsinghvi22, i noticed that cherry pick can be an option, is there something I can help to cherypick this into 4.4?

**Comment by ojhughes** [comment]
@EvertonSA sure we can do this. I will take this opportunity to encourage you to upgrade to the 5.x chart as there are many improvements 😀

**Comment by EvertonSA** [comment]
@ojhughes thanks a lot, I will bring this to my developer team

**Comment by EvertonSA** [comment]
as #125 got merged, i'm closing this issue
