### ISSUE TITLE
[Bug]: new passwordFromSecret option does not work when trying to deploy with argocd (for example)

### ISSUE THREAD

**Issue by jlpnetworx** [neo4j/helm-charts#127]
### Contact Details

mhecker@cmri.org.au

### What happened?

I have started using the standalone chart in version 4.4.16 and tried to use the new passwordFromSecret feature, which works fine if you deploy it directly with helm - however if you use the --dry-run flag or the helm template command, it does not work. The reason is that the helm chart template does a lookup to see if the existing secret exists, which is fine normally. However, when using the --dry-run flag or helm template, it does not work as the lookup of the secret yields nothing as there is no comms with the cluster in that mode. Unfortunately when deploying via argocd, argocd does do a dry-run or local template (not sure which one of the two) first before it deploys it and falls over with an Application conditions error as follows:  Secret my-secret configured in 'neo4j.passwordFromSecret' not found.
To solve this, the Secret lookup in the chart helper would have to be removed.

### Chart Name

Standalone

### Chart Version

4.4.3

### Environment

My environment is not listed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ojhughes** [comment]
Hi @jlpnetworx thanks for raising this. What happens if you create the secret before running the ArgoCD deploy?

**Comment by jlpnetworx** [comment]
Hi, exactly what I described. The issue is in the helper as it looks up if the secret exist. While it does really exist, the way helm works when dry running the template, it can't be checked against the cluster hence yields an empty list and ultimately fails for an argocd deployment.

**Comment by ojhughes** [comment]
We could add a new property such as `neo4j.passwordFromSecretLookup` that defaults to true

**Comment by jlpnetworx** [comment]
That would be a great way to overcome this issue.

**Comment by olympe-operator** [comment]
is there any plan to add this configuration value? it's still not part of latest 4.4 release

**Comment by ojhughes** [comment]
This setting is now --set disableLookups=true because we want to disable lookups beyond just the secret. This flag is released in 4.4.17 and 5.5 helm charts
