### ISSUE TITLE
[Bug]: Bad config value lookup for prometheus svc enabled

### ISSUE THREAD

**Issue by enys** [neo4j/helm-charts#129]
### Contact Details

edward@linkurio.us

### What happened?

Looking at: https://github.com/neo4j/helm-charts/blob/dev/neo4j/templates/neo4j-svc.yaml#L11
and considering : https://neo4j.com/docs/upgrade-migration-guide/current/version-5/migration/breaking-changes/#_configuration_settings_refresh
Specifically : `For example, metrics.enabled is renamed server.metrics.enabled`
and at neo4j startup : `WARN: Use of deprecated setting 'metrics.prometheus.enabled'. It is replaced by 'server.metrics.prometheus.enabled'.`

I this the lookup should be prefixed by `server.`

In this bug template the chart version 5.3.0 is missing in the chart version selector.

### Chart Name

neo4j

### Chart Version

5.3.0

### Environment

Issue seen on all the cloud providers (GCP , AWS , AKS)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harshitsinghvi22** [comment]
thanks @enys  for raising this issue.

This has been fixed in the latest 5.5.0 release
https://github.com/neo4j/helm-charts/releases/tag/5.5.0
