### ISSUE TITLE
Migrating from neo4j-contrib chart

### ISSUE THREAD

**Issue by Sleepy-GH** [neo4j/helm-charts#131]
Hello,

I'm looking for documentation on how to migrate from the deprecated Neo4j-contrib chart to this chart. I've spent some time searching but I can't seem to find anything. Am I overlooking something?

Thank you!

**Comment by harshitsinghvi22** [comment]
https://neo4j.com/docs/operations-manual/5/kubernetes/maintenance/#_migrate_neo4j_from_the_labs_helm_charts_to_the_neo4j_helm_charts_offline
