### ISSUE TITLE
Add slack integration so that we can receive the slack notification once any new release published

### ISSUE THREAD

**Issue by zhangtbj** [neo4j/helm-charts#132]
**Is your feature request related to a problem? Please describe.**
Right now, there is no slack integration for this `neo4j/helm-charts` repo, we cannot get the new release by slack.

**Describe the solution you'd like**
The repo admin can add slack integration for external developers.
Like this: https://github.com/integrations/slack

Thanks!

**Describe alternatives you've considered**

**Additional context**

**Comment by harshitsinghvi22** [comment]
This is resolved now @zhangtbj 

The IT team at Neo4j have added integrated this repo with slack
Firing the below command should work

/github subscribe neo4j/helm-charts

**Comment by zhangtbj** [comment]
It works now.

Thanks!
