### ISSUE TITLE
[Bug]: Merges to dev are overwriting published chart for neo4j/neo4j @ 5.4.0

### ISSUE THREAD

**Issue by chris-pinola-rf** [neo4j/helm-charts#143]
### Contact Details

chrisp@wonder.com

### What happened?

Chart Version: 

Caveat: this all might be intentional but I suspect it's not.

I'm noticing that every time new commits are merged to the `dev` branch, the published artifact for version `5.4.0` of the `neo4j` chart on https://helm.neo4j.com/neo4j gets overwritten.

At least, I suspect this is what's happening, because on 8 Feb 2023 (2 days ago) I was able to use the `.Values.neo4j.nodeSelectorLookup` setting in the chart and today I cannot, but suddenly `.Values.disableLookups` is available to me, and I have been referencing version `5.4.0` of the chart this entire week. As far as I can tell, the only thing that's changed in the meantime is that https://github.com/neo4j/helm-charts/pull/140 was merged.

The reason why I suspect this behavior is unintentional is because [the tag accompanying this version of the chart](https://github.com/neo4j/helm-charts/commits/5.4.0) no longer reflects the artifact which is published to https://helm.neo4j.com/neo4j.

### Chart Name

Standalone

### Chart Version

5.4.0 (wasn't a choice in the issue template)

### Environment

Microsoft Azure

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harshitsinghvi22** [comment]
Hi @chris-pinola-rf 

Unfortunately , one of the bad triggers caused this issue.

Thanks for raising this issue. It has been identified and recitified. 

This should not happen again ideally.

Will try and see i  can revert 5.4.0 to the old state.

But yes, until then you can use --set disableLookups=true to disable all the lookups in helm charts including the nodeSelectorLookup

Thanks,
Harshit

**Comment by chris-pinola-rf** [comment]
Thanks @harshitsinghvi22! In this case, I think I would prefer if you _didn't_ revert to the old state since the original 5.4.0 artifact provided no way to disable the nodeSelectorLookup. 😅

**Comment by harshitsinghvi22** [comment]
@chris-pinola-rf the nodeSelectorLookup and passwordFromSecretLookup are removed and are supported with disableLookups flag. If you set disableLookup to true it will work the same as nodeSelectorLookup to false
disableLookups flag disables all the lookups across the helm charts

**Comment by chris-pinola-rf** [comment]
Understood, but in [the original 5.4.0 tag version of the chart values](https://github.com/neo4j/helm-charts/blob/5.4.0/neo4j/values.yaml), neither `nodeSelectorLookup` nor `disableLookups` exists.

**Comment by harshitsinghvi22** [comment]
Yes...but ideally disableLookup should be part of next release and I will have to revert 5.4.0 so that to incorporate the same in next release....apologies for the inconvenience caused.

However, once the revert of the package is done dev will have the latest new changes and you can use the same until the next release happens.

**Comment by chris-pinola-rf** [comment]
@harshitsinghvi22 I was trying to avoid needing to vendor the chart to get these fixes. Is the `dev` branch published anywhere? If not, is there any chance of publishing a 5.4.1 chart soon?

**Comment by harshitsinghvi22** [comment]
hey @chris-pinola-rf  no the dev branch is not published anywhere..however the good news is 5.5.0 helm charts will be available next Monday (20th Feb) so you should these changes released by Monday evening
