### ISSUE TITLE
Add support for priority classes

### ISSUE THREAD

**Issue by SansGuidon** [neo4j/helm-charts#15]
**Is your feature request related to a problem? Please describe.**
Context : in our production cluster, some workloads such as neo4j database are more critical than others so we need that reflected in terms of priority classes for pods. We need to ensure those workloads have very high priority so our cluster is functional. Unfortunately the Neo4J helm charts do not expose `priorityClassName` attribute, which is not blocking but forces us to find workarounds. 

**Describe the solution you'd like**
Something like https://github.com/neo4j-contrib/neo4j-helm/pull/250 and https://github.com/neo4j/helm-charts/pull/1 
Official documentation: https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/

**Describe alternatives you've considered**
Using kustomize to post-render Neo4j helm chart.

**Additional context**
Related issue : https://github.com/neo4j-contrib/neo4j-helm/issues/227
Related PRs : 
* https://github.com/neo4j/helm-charts/pull/2
* https://github.com/neo4j/helm-charts/pull/1
* https://github.com/neo4j-contrib/neo4j-helm/pull/250
Official documentation: https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/

**Comment by harshitsinghvi22** [comment]
@MorganGeek 
Support for priority classes released in 4.4.9
https://github.com/neo4j/helm-charts/releases/tag/4.4.9
