### ISSUE TITLE
[Bug]: Minimum cluster size forced to be >= 3

### ISSUE THREAD

**Issue by rlch** [neo4j/helm-charts#150]
### What happened?

Hi,

I've noticed that clustering is only enabled when `neo4j.minimumClusterSize` is greater than or equal to 3:
```go
{{- define "neo4j.isClusterEnabled" -}}
      {{- $minClusterSize := index $.Values.neo4j "minimumClusterSize" | default 1 | int -}}
      {{- if ge $minClusterSize 3 -}}
          {{- if not (eq $.Values.neo4j.edition "enterprise") -}}
               {{- fail (printf "Please use enterprise edition for clustering. You can set edition via --set neo4j.edition=enterprise") -}}
          {{- end -}}
            true
      {{- else -}}
            false
      {{- end -}}
  {{- end -}}

```

Is this intended? I haven't found docs for Neo4J 5.x that state this as a constraint.
Thanks

_Note_: The **Chart Version** and **Chart Name** for the issue template has not been updated for 5.x.
I'm running the latest `5.5.0`.

### Chart Name

neo4j

### Chart Version

5.5.0

### Environment

Google Cloud Platform

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harshitsinghvi22** [comment]
hi @rlch  the minimum number of members for a fault tolerant cluster is 3 hence the condition
https://github.com/neo4j/helm-charts/blob/5.5.0/neo4j/Chart.yaml The chart version and chart name are correct

**Comment by rlch** [comment]
Thank you!

**Comment by rlch** [comment]
@harshitsinghvi22 Was referring to the issue template, but no big deal: 
![image](https://user-images.githubusercontent.com/35163478/222408300-77bc529d-6022-4471-a244-e14567a1ba4f.png)

**Comment by harshitsinghvi22** [comment]
ahh thanks for reporting that let me fix it now
