### ISSUE TITLE
[Bug]: Migrating from neo4j-contrib chart

### ISSUE THREAD

**Issue by wufengzlw** [neo4j/helm-charts#168]
### Contact Details

wufeng.zlw@gmail.com

### What happened?

Hi, 

This is not a bug, just some issue 

I'm migrating a 4.4 Cluster (with core and replica nodes) from neo4j-contrib chart to this chart following this guide:
https://neo4j.com/docs/operations-manual/current/kubernetes/maintenance/#_migrate_neo4j_from_the_labs_helm_charts_to_the_neo4j_helm_charts_offline

The first step:
I need to create a 4.4 cluster with this chart:

(1) From the doc, I need to deploy this cluster with multiple charts (https://neo4j.com/docs/operations-manual/5/kubernetes/quickstart-cluster/ )
     But there is no `neo4j/neo4j` in chart version 4.4
     How should I deploy the cluster, is there any deployment doc?

(2) About data migration, the migration doc only provide an offline solution, is that possible to migrate data from original cluster with an alive mode to decrease downtime?

### Chart Name

Cluster

### Chart Version

4.4.16

### Environment

Amazon Web Services

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harshitsinghvi22** [comment]
Hi @wufengzlw 

(1) From the doc, I need to deploy this cluster with multiple charts (https://neo4j.com/docs/operations-manual/5/kubernetes/quickstart-cluster/ )
But there is no neo4j/neo4j in chart version 4.4
How should I deploy the cluster, is there any deployment doc?

 --> the doc that you are referring to is for Neo4j 5 ...i think you need 4.4 documentation..the correct link for it is
https://neo4j.com/docs/operations-manual/4.4/kubernetes/

4.4 --> has separate charts for standalone and cluster-core

(2) About data migration, the migration doc only provide an offline solution, is that possible to migrate data from original cluster with an alive mode to decrease downtime?
--> As of now we do not have any working/ tested solution to migrate data from original cluster with an alive mode to decrease downtime

**Comment by wufengzlw** [comment]
@harshitsinghvi22 
Thank you for the help.

From this doc:
https://neo4j.com/docs/upgrade-migration-guide/current/version-5/migration/cluster/helm-example/

Seems I'll need to do another migration from version 4.4 to 5 with downtime, so 2 disruptive changes:
1. Migrate existing 4.4 cluster from neo4j-contrib chart to this chart
2. Migrate Neo4j cluster from 4.4 to 5

I didn't find it in the doc, but is that possible to migrate 4.4 of neo4j-contrib chart directly to version 5 of this chart?

**Comment by harshitsinghvi22** [comment]
Hi @wufengzlw 

The following doc should help you

https://neo4j.com/docs/upgrade-migration-guide/current/version-5/migration/standalone/helm-example/

Thanks,
Harshit

**Comment by harshitsinghvi22** [comment]
@wufengzlw since we have stopped supporting neo4j-contrib from a long time , i would suggest you to move to the 4.4 helm charts and then migrate to v5.

I believe both approaches would involve taking backup and then importing it.

You can try directly from neo4j-contrib to v5 but please keep a backup of your data incase it does not work out.

**Comment by wufengzlw** [comment]
@harshitsinghvi22 thank you very much for the info!
