### ISSUE TITLE
[Bug]: _helpers.tpl message gives wrong advice when creating passwordFromSecret

### ISSUE THREAD

**Issue by cychainey** [neo4j/helm-charts#170]
### What happened?

Hi,
I was just installing the chart locally and testing the `passwordFromSecret` option. 
It appears the error message is giving the wrong advice. It currently says `Secret examplepassword must contain key NEO4J_DATA`  Think that needs to be `Secret examplepassword must contain key NEO4J_AUTH`.
Not a biggie obviously, but might save someone a bit of head scratching.

Thanks

### Chart Name

Cluster

### Chart Version

5.5.0

### Environment

Local Machine

### Relevant log output

```shell
{{- define "neo4j.secretName" -}}
    {{- if .Values.neo4j.passwordFromSecret -}}
        {{- if not .Values.disableLookups -}}
            {{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.neo4j.passwordFromSecret) }}
            {{- $secretExists := $secret | all }}
            {{- if not ( $secretExists ) -}}
                {{ fail (printf "Secret %s configured in 'neo4j.passwordFromSecret' not found" .Values.neo4j.passwordFromSecret) }}
            {{- else if not (hasKey $secret.data "NEO4J_AUTH") -}}
                {{ fail (printf "Secret %s must contain key NEO4J_DATA" .Values.neo4j.passwordFromSecret) }}
            {{/*The secret must start with characters 'neo4j/`*/}}
            {{- else if not (index $secret.data "NEO4J_AUTH" | b64dec | regexFind "^neo4j\\/\\w*") -}}
                {{ fail (printf "Password in secret %s must start with the characters 'neo4j/'" .Values.neo4j.passwordFromSecret) }}
            {{- end -}}
        {{- end -}}
        {{- printf "%s" (tpl .Values.neo4j.passwordFromSecret $) -}}
    {{- else -}}
        {{- include "neo4j.name" . | printf "%s-auth" -}}
    {{- end -}}
{{- end -}}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ghost** [comment]
thanks @cychainey 

You are absolutely right here. I will fix this quickly.

Thanks once again for reporting this.

**Comment by cychainey** [comment]
No worries, happy to help

**Comment by harshitsinghvi22** [comment]
@cychainey this is fix in https://github.com/neo4j/helm-charts/pull/173
