### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by psolarcz** [neo4j/helm-charts#175]
How can we enable prometheus metrics collection with neo4j helm chart ?

**Comment by harshitsinghvi22** [comment]
https://neo4j.com/docs/operations-manual/current/kubernetes/monitoring/#monitoring-metrics

**Comment by psolarcz** [comment]
@harshitsinghvi22 Does it expose service with metrics? I'm also looking if ServiceMonitor is created?

**Comment by ojhughes** [comment]
@psolarcz You need to create your own ServiceMonitor object, we just expose the metrics endpoints for scraping

**Comment by psolarcz** [comment]
@ojhughes I don't see service with port 2004 either, should it exist?

**Comment by ojhughes** [comment]
Yes the *-admin service should have port 2004 exposed. Are you using Neo4j 4.4.x or 5.x? The config will be slightly different depending on the version

**Comment by psolarcz** [comment]
ok, I found what the problem is, thanks for your support.

Are you planning to add serviceMonitor object?

**Comment by ojhughes** [comment]
> Are you planning to add serviceMonitor object?

Is it required for setting up monitoring when Prometheus is deployed using an operator?

Looking at other Helm charts, I don't see that it is commonly provided so I don't think we should add it

**Comment by psolarcz** [comment]
examples:
https://github.com/bitnami/charts/blob/main/bitnami/postgresql/templates/primary/servicemonitor.yaml
https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/templates/controller-servicemonitor.yaml
https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/templates/servicemonitor.yaml

almost everyone who expose metrics on k8s,  also provides serviceMonitor.

Please consider adding it :) I can open PR if needed.

**Comment by harshitsinghvi22** [comment]
Reopened the issue..to provide support for serviceMonitor

**Comment by harshitsinghvi22** [comment]
@psolarcz This is implemented in v5 and v4.4
https://github.com/neo4j/helm-charts/pull/257
https://github.com/neo4j/helm-charts/pull/256
Will be part of the next upcoming release
