### ISSUE TITLE
[Bug]: 5.7.0 neo4j-loadbalancer.yaml does not include annotations from values

### ISSUE THREAD

**Issue by omriarieli** [neo4j/helm-charts#176]
### What happened?

installed chart version **5.7.0** wanted to create a load balancer service with annotations
result was the annotations were put into labels.
i downloaded the chart locally and moved [this line](https://github.com/neo4j/helm-charts/blob/dev/neo4j/templates/neo4j-loadbalancer.yaml#L38) to be under annotations: and got the expected annotations from my values file.

### Chart Name

Standalone

### Chart Version

5.5.0

### Environment

Google Cloud Platform

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harshitsinghvi22** [comment]
thanks for reporting this @omriarieli 

Will be fixed in the upcoming release

**Comment by harshitsinghvi22** [comment]
this is fixed in the below PR
https://github.com/neo4j/helm-charts/pull/189

Will be part of 5.10.0 release
