### ISSUE TITLE
[Bug]: cluster fails to find fromExistingSecret

### ISSUE THREAD

**Issue by johnstonmatt** [neo4j/helm-charts#179]
### Contact Details

matt.johnston@polyseam.io

### What happened?

After creating a `Secret` and adding it to my cluster,  then specifying the secret name in `values.neo4j.passwordFromSecret`  neo4j is unable to find the Secret.

We are using ArgoCD to deploy the cluster, and are happy to provide any additional info, including a walkthrough of the issue if that would be helpful.

### Chart Name

Cluster

### Chart Version

5.5.0

### Environment

Issue seen on all the cloud providers (GCP , AWS , AKS)

### Relevant log output

```shell
Error: execution error at (neo4j/templates/_helpers.tpl:346:19): Secret neo4j-auth configured in 'neo4j.passwordFromSecret' not found Use --debug flag to render out invalid YAML
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ojhughes** [comment]
Hi, please set `disableLookups: false` when using ArgoCD

**Comment by johnstonmatt** [comment]
@ojhughes we've confirmed this issue applies uniquely to ArgoCD, using this config https://github.com/harshil4076/neo4j-secret-test. 

It is still broken in Argo even with `disableLookups: false` but not when we use `helm install` without Argo, maybe there is some other ingredient we are missing?

**Comment by ojhughes** [comment]
Ah apologies I meant disableLookups: true

Argo uses helm template, which doesn't work with helm lookups

**Comment by johnstonmatt** [comment]
That's what we needed, thank you!
