### ISSUE TITLE
Neo4j browser behind ingress with TLS encryption

### ISSUE THREAD

**Issue by chris-adam-b12** [neo4j/helm-charts#181]
Hello,

I'm sorry if this is not the right place to make such request. I have deployed Neo4jJ on Kubernetes using this helm chart. I would like to expose the Neo4J browser so that the staff can interact with the graphical interface.

The ideal solution would be to use Ingress Nginx with Cert Manager. I managed to expose the browser with this technology but it doesn't work for the Bolt port. Therefore, I customised my Ingress Nginx to expose the port 7687 (https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/).

The problems are that custom TCP services are not encrypted, and I still not able to login through the problem for some websocket errors (WebSocket connection to 'wss://example.com:7687/' failed).

Have you encountered this situation before ? Do you have any solution already ?

Regards,
Chris

**Comment by ojhughes** [comment]
Hi @chris-adam-b12 - this is being worked on. Check out this PR to see the intended approach https://github.com/neo4j/helm-charts/pull/180

**Comment by chris-adam-b12** [comment]
Hello @ojhughes ,
Thank you for that quick answer ! When is it expected to be delivered in the stable release version (a week, a month, more ?) ?

**Comment by ojhughes** [comment]
Hey @chris-adam-b12 - It will be at least a month as I am on vacation for 2 weeks, then need to add more tests / docs / perform a release.

Feel free to experiment with that branch in the mean time as it is a standalone solution that deploys an HAProxy instance for the ingress controller to connect to using port 80 / 443

**Comment by brucetony** [comment]
I am also very interested in this as we have been trying to create such a deployment using a proxy as you have done. I will test out what you have so far, thanks so much for working on this solution!

**Comment by martintamb12** [comment]
Hi @ojhughes, do you have any good news about this great feature?

**Comment by harshitsinghvi22** [comment]
This is addressed with the release of neo4j-reverse-proxy helm chart in 5.12.0
https://neo4j.com/docs/operations-manual/5/kubernetes/accessing-neo4j-ingress/
