### ISSUE TITLE
Support comma separated databases in backup

### ISSUE THREAD

**Issue by shubham030** [neo4j/helm-charts#188]
**Is your feature request related to a problem? Please describe.**
If there are multiple databases in the dbms we should be able to backup them.

**Describe the solution you'd like**
The backup helm values should take comma-separated databases and all can be backed up from a single cron

**Describe alternatives you've considered**
-  Deploy cron per database for backup
- Currently, I am using [self-developed](https://github.com/MathGaps/helm-charts/tree/main/charts/neo4j-backup) helm chart which uses neo4j and gcs-fuse

**Comment by harshitsinghvi22** [comment]
Hi @shubham030 

As per the documentation neo4j-admin does not support multiple databases via the --database option

https://neo4j.com/docs/operations-manual/current/backup-restore/online-backup/

However, if you want to backup all the databases you can just mention * in the values.yaml for the database field and all the databases will be backed up

Hope this helps.

Thanks
Harshit

**Comment by harshitsinghvi22** [comment]
We can definitely provide support for comma separated databases but that will be a workaround and not through neo4j-admin 

Let me know if the * solves your problem

**Comment by shubham030** [comment]
Hi @harshitsinghvi22 

We want to selectively backup the database, so '*' won't solve the issue. As for the workaround right now that is what we are using like running the `neo4j-admin database backup` in a loop for all the comma-separated values.

**Comment by harshitsinghvi22** [comment]
Appreciate your reply @shubham030 

Will take a look at this and get this implemented before next release.

Thanks for raising this feature request.

**Comment by shubham030** [comment]
That sounds good @harshitsinghvi22, let me know if you would like any help on this.

**Comment by harshitsinghvi22** [comment]
This is completed for both v5 and v4.4.

Will be part of 5.10.0 and 4.4.22

https://github.com/neo4j/helm-charts/pull/198
https://github.com/neo4j/helm-charts/pull/199
https://github.com/neo4j/helm-charts/pull/200
