### ISSUE TITLE
Add nodeselector support for backup cronjobs

### ISSUE THREAD

**Issue by davidlrosenblum** [neo4j/helm-charts#197]
Neo4j Supports both ARM and X64 and there maybe node pools for different purposes in the same K8 Cluster
We need to direct the backup jobs so that the backup runs on the appropriate Node Pool

**Describe the solution you'd like below to get the pod running the right node pool ***
Something like
nodeSelector:
__backup-node-pool: "yes"

**Comment by harshitsinghvi22** [comment]
Added support them in the following PR's
https://github.com/neo4j/helm-charts/pull/204
https://github.com/neo4j/helm-charts/pull/201

Will be part of 5.10.0 release.
