### ISSUE TITLE
Deployment through Terraform Helm provider 

### ISSUE THREAD

**Issue by colintkn** [neo4j/helm-charts#211]
Has anyone successfully deployed a cluster size of 3 through the Terraform helm provider? So far, the cluster is unable to form. (usually the first core cannot be connected to). I've tried running helm commands the traditional way and the cluster forms.  

I am deploying it via Terraform. I make sure that, I create the cores one by one through targets. 
`terraform apply -target helm_release.neo4j[0]`
`terraform apply -target helm_release.neo4j[1]`
`terraform apply -target helm_release.neo4j[2]`

Here's the resource. 
```
resource "helm_release" "neo4j" {
  count = var.cluster_size
  name      = "neo4j-${count.index}"
  chart     = local.chart_repository
  version   = var.neo4j_helm_release_version
  namespace = kubernetes_namespace.neo4j.id

  values = [templatefile("${path.module}/templates/neo4j-values.yml",
    {
      cluster_size = var.cluster_size
      password = random_password.neo4j.result
      # node_selector = local.node_selector
      storage_class_name = local.aws_ebs_csi["storage_class_name"]
      az = local.availability_zones[count.index]
      db_name = "neo4j-${count.index}"
    }
  )]
}
```

Just wondering if anyone successfully ran it through Terraform.

**Comment by harshitsinghvi22** [comment]
@colintkn i will be honest here by saying that I have never used helm charts with terraform nor I have any experience with terraform however for the cluster to be formed you need to set minimumClusterSize to the required number.

I don't see this field being referenced in the values set by you in terraform. Might be I am missing something here.

But give the above suggestion a try and let me know.

**Comment by colintkn** [comment]
Hi @harshitsinghvi22 , 
The helm chart work but has to be deployed in sequence by targetting the resources (fyi for those deploying through terraform) 

Thanks for you help!

**Comment by sfc-gh-pkommini** [comment]
@colintkn could you describe in what order you setup the resources? Were you able to set it up on AWS?
