### ISSUE TITLE
Feature to add annotations to serviceAccount 

### ISSUE THREAD

**Issue by colintkn** [neo4j/helm-charts#212]
**Is your feature request related to a problem? Please describe.**
ServiceAccount created via the podSpec has no rolebinding to the roles that are created by default.

```
podSpec: 
#   # Name of service account to use for the Neo4j Pod (optional)
#   # this is useful if you want to use Workload Identity to grant permissions to access cloud resources e.g. cloud object storage (AWS S3 etc.)
   serviceAccountName: ${service_account_name}
```

**Describe the solution you'd like**
Feature to add annotations to the default serviceAccount. 

**Additional context**

**Comment by harshitsinghvi22** [comment]
Hi @colintkn 

You can create your own serviceaccount with annotations and the appropriate roles and rolebindings and use that serviceaccountname in the values.yaml via podspec.serviceaccountname.


Please let us know if the above does not solve your query.

Thanks
Harshit

**Comment by colintkn** [comment]
Hi Harshit, 

Thanks for the workaround. Is there a reason for not supporting annotations? And is there intention to support this feature in the future (i think older helm charts supported this)

**Comment by harshitsinghvi22** [comment]
@colintkn since we provide support for adding your own customized serviceaccount I don't see any extra benefits of adding support for annotations in the default serviceaccount provided by helm chart.
