### ISSUE TITLE
[Bug]: Adding a gds node to a standalone cluster gives error 

### ISSUE THREAD

**Issue by kavitak123** [neo4j/helm-charts#218]
### Contact Details

friscotutor15@gmail.com

### What happened?

Adding a gds node to a standalone cluster gives error 
"Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: Service "myneo-lb-neo4j" in namespace "neo4j" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "mygds": current value is "myneo"" , even after setting  selector:   helm.neo4j.com/clustering: "false" config:   initial.server.mode_constraint: "SECONDARY"   server.cluster.system_database_mode: "SECONDARY"

Trying to add gds node to a standalone node , minimumClusterSize specified as 1.
The chart for cluster and standalone are the same , chart v 5.10

### Chart Name

Cluster

### Chart Version

5.5.0

### Environment

Google Cloud Platform

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harshitsinghvi22** [comment]
@kavitak123 can you try doing the same but with minimumClusterSize set to 2?

The first install can be a primary and the second install can be a secondary

**Comment by harshitsinghvi22** [comment]
@kavitak123 my previous comment was incorrect.

As of now , a single primary and a single standalone would not be possible as you need atleast 3 members for a cluster

However , with 3 members you can achieve the state of 2 primary and 1 secondary via this method

- install a 3 instance cluster (all primary by default)
- use [cypher commands](https://neo4j.com/docs/operations-manual/current/clustering/databases/#_alter_topology) to change topology of the specific database
- use [cypher command](https://neo4j.com/docs/operations-manual/current/clustering/servers/#alter-server-options) to alter one particular server as secondary
- This way you will have 2 primary and 1 secondary

Will keep this open to see if we can come up with some way to support 1 primary and 1 secondary

**Comment by harshitsinghvi22** [comment]
Working with internal team on this as there is on straight forward solution to this...this will require product changes which have been forwarded to the concerned team.

As of now for gds you would need a minimum of 2 primary and 1 secondary

**Comment by harshitsinghvi22** [comment]
@kavitak123  this is implemented and Neo4j Helm Charts now support the 1primary + N Secondary scenario
https://neo4j.com/docs/operations-manual/current/kubernetes/quickstart-analytics-cluster/
