### ISSUE TITLE
Implement affinity and tolerations in neo4j-admin chart 

### ISSUE THREAD

**Issue by headyj** [neo4j/helm-charts#219]
nodeSelector is not enough if you want to dedicate a specific Kubernetes node for backups, we also need affinity and tolerations.

Please also cherry pick on 4.4 branch as well, as it seems that the CronJob is not exactly the same on both branches

Related PR: https://github.com/neo4j/helm-charts/pull/214

**Comment by harshitsinghvi22** [comment]
this is implemented and will be part of next release
https://github.com/neo4j/helm-charts/pull/223
https://github.com/neo4j/helm-charts/pull/222
