### ISSUE TITLE
[Bug]: disabling dbms.backup.enabled doesn't remove the backup port from the service

### ISSUE THREAD

**Issue by danydrouin** [neo4j/helm-charts#227]
### Contact Details

ddrouin@ca.ibm.com

### What happened?

in https://github.com/neo4j/helm-charts/blob/dev/neo4j/templates/neo4j-svc.yaml, the backupEnabled var is never used to disable the backup service port.

Also the statefulset should not expose the backup container port if `dbms.backup.enabled=false`

https://github.com/neo4j/helm-charts/blob/dev/neo4j/templates/neo4j-statefulset.yaml#L115C21-L116

### Chart Name

Cluster

### Chart Version

5.5.0

### Environment

Local Machine

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harshitsinghvi22** [comment]
thanks @danydrouin  for raising this issue.

This should be resolved in the next upcoming release

**Comment by harshitsinghvi22** [comment]
https://github.com/neo4j/helm-charts/pull/234
https://github.com/neo4j/helm-charts/pull/233
this feature is implemented in the above PR's for v5 and v4.4
These will be the part of the upcoming release
