### ISSUE TITLE
[Bug]: podAntiAffinity object not working

### ISSUE THREAD

**Issue by danydrouin** [neo4j/helm-charts#228]
### Contact Details

ddrouin@ca.ibm.com

### What happened?

the current `podAntiAffinity` is too restrictive for our purpose, we would like to use `preferredDuringSchedulingIgnoredDuringExecution`.

we want to override the podAntiAffinity by using our own object as stated in the values.yaml but this is not working.  the logic really only works for true/false.

https://github.com/neo4j/helm-charts/blob/dev/neo4j/templates/_helpers.tpl#L321-L338

values.yaml
```  
# Anti Affinity
  # If set to true then an anti-affinity rule is applied to prevent database pods with the same `neo4j.name` running on a single Kubernetes node.
  # If set to false then no anti-affinity rules are applied
  # If set to an object then that object is used for the Neo4j podAntiAffinity
  podAntiAffinity: true
```

Can the chart be enhanced to support a custom object for podAntiAffinity as mentioned in the values.yaml?

### Chart Name

Cluster

### Chart Version

5.5.0

### Environment

Local Machine

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harshitsinghvi22** [comment]
thanks for raising the issue @danydrouin .

This is indeed a bug. Will take a look and add support for podAntiAffinity object in the next upcoming release.

**Comment by harshitsinghvi22** [comment]
https://github.com/neo4j/helm-charts/pull/231
https://github.com/neo4j/helm-charts/pull/232
This is fixed in the above Pr's for both Neo4j v5 and v4.4 . This will be part of the next upcoming release
