### ISSUE TITLE
[Bug]: duplicate server.https.enabled

### ISSUE THREAD

**Issue by dperehudovautodoc** [neo4j/helm-charts#230]
### Contact Details

d.perehudov@autodoc.eu

### What happened?

I use flux v2 to deploy neo4j to kubernetes
When i set ssl.https.privateKey.secretName, then duplicate server.https.enabled was appeared in ConfigMap default-config
And flux v2 generates error
`Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
  line 49: mapping key "server.https.enabled" already defined at line 24`

### Chart Name

Cluster

### Chart Version

5.5.0

### Environment

Google Cloud Platform

### Relevant log output

```shell
Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
  line 49: mapping key "server.https.enabled" already defined at line 24
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harshitsinghvi22** [comment]
this is fixed in the below PR
https://github.com/neo4j/helm-charts/pull/235

Will be part of the upcoming helm release
