### ISSUE TITLE
Neo4j Backup for AWS should support "IAM roles for service accounts"

### ISSUE THREAD

**Issue by minimax75** [neo4j/helm-charts#238]
Hi,

We are currently evaluating an upgrade from v4.4 to v5 and the corresponding Helm installation on Kubernetes. Up until now, we've been using the community Helm chart for installation and backup which can be found at https://github.com/neo4j-contrib/neo4j-helm.

If I understood the documentation correctly (https://neo4j.com/docs/operations-manual/current/kubernetes/operations/backup-restore/), only users with programmatic access, via an access key and secret, are supported.

We use Kubernetes Service Accounts to access resources on AWS. These service accounts assume roles that grant the necessary rights (https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html).

My question is whether there are any plans to implement this function or if it is on the roadmap.

Thank you very much!

Max

**Comment by harshitsinghvi22** [comment]
Hi @minimax75 , yes we are working on bringing support for workload identity to the neo4j-admin helm chart...You should see this implemented in the upcoming future releases

**Comment by minimax75** [comment]
Hello @harshitsinghvi22,

Great to hear that! Looking forward to use it.

Best Regards
Max

**Comment by harshitsinghvi22** [comment]
This is implemented in the following PR's for v5 and v4.4
https://github.com/neo4j/helm-charts/pull/241
https://github.com/neo4j/helm-charts/pull/242

Will be part of the next upcoming release
