### ISSUE TITLE
[feature request] provide configmap name for server-logs.xml

### ISSUE THREAD

**Issue by ikwattro** [neo4j/helm-charts#239]
Looking at the helm charts, I couldn't find a way to provide the name of the configmap containing my server-logs.xml config rather than adding the full xml definition in the values file.

Is it something that's planned on the roadmap ? 

Thx

**Comment by harshitsinghvi22** [comment]
@ikwattro this is possible by using additionalVolumes and additionalVolumeMounts already supported in the helm chart.
You will also need to change the path of the xml files via the neo4j config using the below configuration
server.logs.config
server.logs.user.config

**Comment by ikwattro** [comment]
Thank you, this is much more complex than adding the xml inside the values.yml then so we will stick with that approach for now, bookmarking in case the current solution becomes too verbose inside the values file.

Thanks again.

**Comment by harshitsinghvi22** [comment]
@ikwattro is additional volumes and additionalVolumeMounts complex ? If yes , can you please explain me the difficulty in using it for your usecase and that can help us in understanding whether to provide configmap name for server-logs.xml or not

**Comment by harshitsinghvi22** [comment]
closing this request as this can be implemented through additionalVolumes and additionalVolumeMounts
