### ISSUE TITLE
[Bug]: neo4j-standalone version 5 missing

### ISSUE THREAD

**Issue by jimsmith** [neo4j/helm-charts#243]
### Contact Details
this ticket

### What happened?

A new installation of a single standalone deployment there is no `5` version 

I then stumbled on this https://github.com/neo4j/neo4j/issues/13311 

Should I be using `neo4j/neo4j-standalone` or `neo4j/neo4j` ?

From https://neo4j.com/docs/operations-manual/5/kubernetes/quickstart-standalone/server-setup/  this differs 

```
$ helm search repo neo4j
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION                                       
neo4j/neo4j                             5.12.0          5.12.0          Neo4j is the world's leading graph database       
neo4j/neo4j-admin                       5.12.0          5.12.0          Neo4j is the world's leading graph database       
neo4j/neo4j-cluster-core                4.4.26          4.4.26          Neo4j is the world's leading graph database       
neo4j/neo4j-cluster-headless-service    4.4.26          -               Neo4j is the world's leading graph database       
neo4j/neo4j-cluster-loadbalancer        4.4.26          -               Neo4j is the world's leading graph database       
neo4j/neo4j-cluster-read-replica        4.4.26          4.4.26          Neo4j is the world's leading graph database       
neo4j/neo4j-docker-desktop-pv           4.4.26          -               Sets up persistent disks suitable for simple de...
neo4j/neo4j-gcloud-pv                   4.4.26          -               Sets up persistent disks suitable for simple de...
neo4j/neo4j-headless-service            5.12.0          -               Neo4j is the world's leading graph database       
neo4j/neo4j-persistent-volume           5.12.0          -               Sets up persistent disks suitable for a Neo4j H...
neo4j/neo4j-reverse-proxy               5.12.0          5.12.0          Sets up an http server and a reverse proxy for ...
neo4j/neo4j-standalone                  4.4.26          4.4.26          Neo4j is the world's leading graph database   
```

Also I note there is no `4.4.26` to select when creating this issue, it's a bit rigid so I just picked the closest 

### Chart Name

Standalone

### Chart Version

4.4.18

### Environment

Local Machine

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harshitsinghvi22** [comment]
@jimsmith For Neo4j v5 please read the documentation here
https://neo4j.com/docs/operations-manual/current/kubernetes/quickstart-standalone/prerequisites/

**Comment by jimsmith** [comment]
@harshitsinghvi22  thanks so just to confirm based on that documentation then just ignore  `neo4j/neo4j-standalone` `4.4.26` then ?

**Comment by harshitsinghvi22** [comment]
For v5 you should be using neo4j/neo4j
For v 4.4 you should be using neo4j/neo4j-standalone installation ,with 4.4.26 being the latest

**Comment by harshitsinghvi22** [comment]
v4.4 documentation
https://neo4j.com/docs/operations-manual/4.4/kubernetes/quickstart-standalone/prerequisites/

**Comment by jimsmith** [comment]
Perfect thank you @harshitsinghvi22 👍
