### ISSUE TITLE
Ability to specify `dnsPolicy`

### ISSUE THREAD

**Issue by cpboyd** [neo4j/helm-charts#264]
**Is your feature request related to a problem? Please describe.**
There's a `spec.dnsPolicy` supported on Kubernetes pods, but this isn't able to be set by the chart currently:
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy

**Describe the solution you'd like**
An option to set this via values YAML rather than having to patch the helm release after install.

**Describe alternatives you've considered**
Internally, we've used `helmfile` to patch the resources in the past but that's not compatible with ArgoCD which we're moving our deployments to.

**Additional context**
N/A

Edit: remove references to airflow and link to Kubernetes docs

**Comment by harshitsinghvi22** [comment]
@cpboyd thanks for raising this issue.
I have no idea what apache airflow is. 
Can you share some more info on where the dnsPolicy needs to be specified ? 
what it is ?
 how it helps ? 
what problem it will solve for you? 
Any other existing db's that provide support for apache airflow in their own helm charts?

**Comment by harshitsinghvi22** [comment]
is it this @cpboyd  ?
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy

**Comment by cpboyd** [comment]
@harshitsinghvi22 Ah, yes. That's it. Sorry, I got confused because we're using airflow to spin up neo4j internally.

**Comment by cpboyd** [comment]
@harshitsinghvi22 to answer your earlier question:

> how it helps ? what problem it will solve for you?

For our [AWS Fargate](https://docs.aws.amazon.com/eks/latest/userguide/fargate.html) deployments of Neo4j, we were testing `"Default"` (which per [the Kubernetes documentation](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy) isn't actually the default `dnsPolicy`).

We've been using the actual **_default_** `dnsPolicy` of `"ClusterFirst"` for all other deployments.

The engineer who made this change is no longer with the company, but I'm guessing we had some DNS resolution issues with Fargate that necessitated the change.

**Comment by harshitsinghvi22** [comment]
@cpboyd this is implemented in the below PR's
https://github.com/neo4j/helm-charts/pull/292
https://github.com/neo4j/helm-charts/pull/291
And they will be part of the next upcoming helm charts release for both v5 and v4.4
