### ISSUE TITLE
Add support for "hosts" in the reverse proxy ingress configuration

### ISSUE THREAD

**Issue by harshitsinghvi22** [neo4j/helm-charts#270]
this is a copy of the below issue
https://github.com/neo4j/docs-operations/issues/1185

**Comment by webcoderz** [comment]
Same here this will fix a problem I have where if the domain is not routing it will redirect to neo4j dashboard

**Comment by harshitsinghvi22** [comment]
Apologies @webcoderz @genft-robot . Have been out on Christmas break and couldn't work on this . This should be fixed by next week and will be available in the next release

**Comment by harshitsinghvi22** [comment]
this is fixed in the PR's for both v5 and v4.4 and will be part of the upcoming helm charts release
https://github.com/neo4j/helm-charts/pull/286
https://github.com/neo4j/helm-charts/pull/285
