### ISSUE TITLE
Allow to specify the node ports when the "load balancer" service type is NodePort

### ISSUE THREAD

**Issue by gmonceyron** [neo4j/helm-charts#271]
**Is your feature request related to a problem? Please describe.**
As a constraint from the k8s cluster I'm using, I need to use a service of type NodePort -which gets registered in an external consul- to expose the http and bolt ports. I would like to be able to pin the ports that are exposed instead of getting random ones.

**Describe the solution you'd like**
The "load balancer" service template could specify the nodePort when provided as a value for each port, otherwise no default value to keep the current solution.

**Describe alternatives you've considered**
For now I'm using a fork where I tampered with this template.

**Comment by harshitsinghvi22** [comment]
This is implemented in the below PR's for both v4.4 and v5 and will be part of the upcoming helm charts release
https://github.com/neo4j/helm-charts/pull/299/files
https://github.com/neo4j/helm-charts/pull/300/files
