### ISSUE TITLE
unable to login to neo4j with the default creadential after installing neo4j with a hem installation

### ISSUE THREAD

**Issue by shettypriy** [neo4j/helm-charts#306]
Hello,

I have set up an AWS EKS cluster and installed neo4j using helm installation and it is installed successfully. I am using the service type loadbalancer and accessing the neo4j browser URL with Load balancer DNS name:7474. I am trying to login to the neo4j server using the EKS secret , but I am unable to login and it gives me the error `Neo.ClientError.Security.Unauthorized: The client is unauthorized due to authentication failure.`

I am using the chart version 5.13 . Argocd is installed as part of EKS cluster which takes care of the helm installation

**Comment by shettypriy** [comment]
Can someone please help me here? I need to implement this in production env

**Comment by harshitsinghvi22** [comment]
@shettypriy the error message indicates the password provided by you at the time of login is incorrect.
If you have installed Neo4j via a secret created by you, please use that password for login.
If you are using the automatic generated password , you can retrieve the password from the 'neo4j-auth' secret in your respective namespace.

**Comment by harshitsinghvi22** [comment]
closing this as no response received from the user and the issue is not reproducible
