### ISSUE TITLE
Add support for tolerations

### ISSUE THREAD

**Issue by MickeyShnaiderman-RecoLabs** [neo4j/helm-charts#31]
The Helm chart doesn't support [Tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/).

On our side, we did a quick fix until then: https://github.com/RecoLabs/helm-charts/commit/1cdf14127fda67f906abe9e538afe0fc543b1f60

**Comment by harshitsinghvi22** [comment]
Thanks @MickeyShnaiderman-RecoLabs for raising this issue.

We have opened a card for this feature and it will be release in the upcoming release cycles

Appreciate your time and effort in raising this issue with us.

**Comment by harshitsinghvi22** [comment]
@MickeyShnaiderman-RecoLabs we just released 4.4.10 version of helm charts which provides support for tolerations
https://github.com/neo4j/helm-charts/releases/tag/4.4.10
