### ISSUE TITLE
[Bug]: Secret secret-neo4j configured in 'neo4j.passwordFromSecret' not found

### ISSUE THREAD

**Issue by predhme** [neo4j/helm-charts#313]
### What happened?

- **Neo4j Chart Version:** [5.17.0](https://github.com/neo4j/helm-charts/releases/tag/5.17.0) (note: this was not an option in the dropdown)
- **k8s Server Version:** v1.27.5+k3s1
- **kubectl version:** v1.28.2
- **helm version:** 3.12.3

The Error (NOTE: I have the chart downloaded and exploded directly in my charts directory): 
```
Error: execution error at (data/charts/neo4j/templates/_helpers.tpl:350:19): Secret secret-neo4j configured in 'neo4j.passwordFromSecret' not found
``` 

I only get this error when running a `helm template .` It is worth mentioning that I am able to `helm install . neo4j` fine. I was able to follow the directions on this [page](https://neo4j.com/docs/operations-manual/current/kubernetes/accessing-neo4j/#_access_neo4j_using_kubectl_for_troubleshooting)  to properly configure access the pod and prove connection using `kubctl` and the `cypher-shell`. 

I use helm for local development of charts, but we actually use ArgoCD to deploy our charts. ArgoCD does not do `helm install` commands. Instead it does `helm template` and then does `kubectl apply`. Sadly ArgoCD fails with the same error. 

Here are my relevant values:

```yaml
neo4j:
  enabled: true
  fullnameOverride: neo4j
  neo4j:
    name: "neo4j"
    passwordFromSecret: "secret-neo4j"
    acceptLicenseAgreement: "yes"
 ```
 
Although I know the secret exists as I am able to authenticate to the deployed pod (when using `helm install`), but to further prove it exists:
 
 ```
 kubectl get secrets
NAME                 TYPE                DATA   AGE
secret-neo4j     Opaque           4           32m
```

### Chart Name

Neo4j

### Chart Version

5.12.0

### Environment

Local Machine

### Relevant log output

```
Error: execution error at (data/charts/neo4j/templates/_helpers.tpl:350:19): Secret secret-neo4j configured in 'neo4j.passwordFromSecret' not found
``` 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by predhme** [comment]
Ok, I figured it out. The `disableLookups` is what I needed.

**Comment by bompi88** [comment]
@predhme Thanks for responding with the solution
