### ISSUE TITLE
[Bug]: neo4j-cronjob should allow securityContext setup at the container and pod level 

### ISSUE THREAD

**Issue by aguealejandro** [neo4j/helm-charts#349]
### Contact Details

guegarale@gmail.com

### What happened?

We are running database backup jobs using the neo4j-cronjob helm chart, however we are unable to get it fully to work in AKS. The main reason is that **securityContext.allowPrivilegeEscalation** needs to be set to **false** at the CONTAINER level. Currently **securityContext** is only set at the POD Level https://github.com/neo4j/helm-charts/blob/8bffca18960fcdff9ed677735d404edd76632937/neo4j-admin/templates/neo4j-cronjob.yaml#L41, as we can see on the following documentation, it needs to be done at the container level as well https://kubernetes.io/docs/tasks/configure-pod-container/security-context/ 

##Alternatives
Currently we had to fork the repo and clone the neo4j-admin chart into our repo in order to unblock ourselves, but ideally we would like to point to the official updated version. 

### Chart Name

Neo4j Admin

### Chart Version

5.12.0

### Environment

Microsoft Azure

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bfeshti** [comment]
Fixed in https://github.com/neo4j/helm-charts/pull/360
