### ISSUE TITLE
Missing `fullNameOverride` and `nameOverride` capabilities

### ISSUE THREAD

**Issue by mansur-abdirimov** [neo4j/helm-charts#38]
**Is your feature request related to a problem? Please describe.**
We create umbrella charts to compose and deploy multiple charts(chart dependencies) as part of one release. Within the scope of the Umbrella Chart we tend to deploy multiple instances the same chart. As example imagine deployment of two separate Neo4J instances dedicated to specific purpose within deployed within one release. To enable such use case charts usually provide possibility to override resource names through `fullNameOverride` and `nameOverride` values.

**Describe the solution you'd like**
Enable the use case by providing resource name overrides through `fullNameOverride` and `nameOverride` values. As a reference 
 you could refer to this [feature request](https://github.com/neo4j-contrib/neo4j-helm/issues/45) in neo4j-helm Labs Helm chart that introduced the same functionality.

**Comment by mohammadsrahman** [comment]
I had the same issues while using this new chart. Looks like they use:

```
neo4j:
  name: neo4j
```

But they are using {{ .Release.Name }} everywhere. Anyway I managed to pull it down and change it. In the Old chart repository i did make a few PR's which were merged but it doesn't look like anyone is watching or accepting any in here. I am happy to create one as i feel this chart is way too over complicated. 

See me PR for the changes.

https://github.com/neo4j/helm-charts/pull/42

**Comment by anantheshadiga** [comment]
I am trying to use neo4j's as a dependent chart. But as `{{ Release.Name }}` is used everywhere in the code, It is using release name of the parent chart, because of which it is conflicting with the service name of parent charts service name.

**Comment by ikwattro** [comment]
Subscribing to this issue for following.
