### ISSUE TITLE
Missing Features

### ISSUE THREAD

**Issue by alxndr13** [neo4j/helm-charts#4]
Hey guys,

thanks for providing the new helm charts, we're still missing some features though, which were kinda handy in the old (now deprecated) [helm chart](https://github.com/neo4j-contrib/neo4j-helm):

- the ability to define databases to create in an initial deployment
- the ability to backup / restore to and from different cloud providers - see: https://neo4j.com/labs/neo4j-helm/1.0.0/backup/#_backup_storage
- the ability to use / define imagePullSecrets

Again: thanks a lot for your work!

**Comment by harshitsinghvi22** [comment]
Hi @alxndr13 ,

Thanks for raising this issue with us.

I am happy to share that we have recently launched 4.4.4 version of helm charts which provides support for imagePullSecrets

Documentation : https://neo4j.com/docs/operations-manual/current/kubernetes/maintenance/#imagepullsecrets

The backup feature is in our backlog and it will be made available in the future

It would be really helpful if you could provide a link or some more info on this feature "the ability to define databases to create in an initial deployment"

Thanks,
Harshit

**Comment by alxndr13** [comment]
Hi @harshitsinghvi22,

thanks for the heads up! Regarding: `the ability to define databases to create in an initial deployment`, i mixed something up there. I was thinking of this part: 
https://neo4j.com/labs/neo4j-helm/1.0.0/restore/#_restore_environment_variables_for_the_init_container

and somehow thought this is how databases can be provisioned in an initial deployment, but that was not the case. In my case i already got backups from the specified databases and so they got "initally" created. 😆  sorry for the confusion.

**Comment by org-ci-cd** [comment]
I would add that nodeSelector was quite useful too, to deploy neo4j container on isolated machines.
edit: I see nodeSelector is getting worked on here https://github.com/neo4j/helm-charts/pull/29

Seems we're also missing the additionalVolumes properties so we can easily add more volumes to the pod.
I was using it to mount a configmap for custom backup restoration during container boot.
From the old helm chart: https://github.com/neo4j-contrib/neo4j-helm/blob/master/values.yaml#L153

Thanks !

**Comment by harshitsinghvi22** [comment]
Hi @alxndr13 

The nodeselector feature is in works and will be released pretty soon.
I will take a look at the volume query and get back to you 

Thanks
Harshit

**Comment by harshitsinghvi22** [comment]
Hi @alxndr13 

NodeSelector feature is out now with 4.4.5 release
https://neo4j.com/docs/operations-manual/4.4/kubernetes/maintenance/#NodeSelector

Thanks,
Harshit

**Comment by harshitsinghvi22** [comment]
Hi @alxndr13 

May , I please request you to close this issue and raise a separate issue for each of the features. 

Thanks,
Harshit

**Comment by org-ci-cd** [comment]
hey @harshitsinghvi22  just did for my request 
https://github.com/neo4j/helm-charts/issues/40

Thank you very much !

**Comment by org-ci-cd** [comment]
Ah @harshitsinghvi22  just realized you never rebuilt the 4.4.5 helm version though ! Can't try it hehe

**Comment by harshitsinghvi22** [comment]
Hi @org-ci-cd 

The 4.4.5 helm version is already build and present here.

https://github.com/neo4j/helm-charts/releases/tag/4.4.5

NodeSelector feature is part of it.

Thanks,
Harshit

**Comment by harshitsinghvi22** [comment]
The index.yaml was missing the 4.4.5 entry...which has been added now....thanks for bringing this to our notice

**Comment by harshitsinghvi22** [comment]
Hi @alxndr13 

Can we please close this issue ?

Please raise a separate ticket for any of the pending features.

Thanks,
Harshit

**Comment by harshitsinghvi22** [comment]
thanks @alxndr13  for closing this issue
