### ISSUE TITLE
The new helm chart is missing the additionalVolumes property that the old one had

### ISSUE THREAD

**Issue by org-ci-cd** [neo4j/helm-charts#40]
Hello ! 

Here is the property from the old helm chart I'm talking about
https://github.com/neo4j-contrib/neo4j-helm/blob/master/values.yaml#L153

I was using that to add more volumes to the pod. 
With this I was able to mount a configmap script into a init-container that automatically restore the latest neo4j backup taken if the PVC is empty. That was pretty useful to me.

Are you guys thinking of implementing this back in the new one ?
Thanks !

**Comment by harshitsinghvi22** [comment]
@org-ci-cd this is added to the latest release of 4.4.10 helm charts
https://github.com/neo4j/helm-charts/releases/tag/4.4.10
