### ISSUE TITLE
Add support for configuring Service ExternalTrafficPolicy Settings

### ISSUE THREAD

**Issue by iahmad-khan** [neo4j/helm-charts#52]
We deployed a cluster of three cores using helm, and the default setting for ExternalTrafficPolicy is not working with exposing bolt as external Loadbalancer.

When we manually edit the service and change the traffic Policy to Cluster, it works.

But there is no configuration option for that while deploying the chart.

**Comment by harshitsinghvi22** [comment]
Hi @iahmad-khan 

Thanks for raising this issue.

Yes, currently externaltrafficpolicy is not configurable via values.yaml

Can you please explain more on your verification process "the default setting for ExternalTrafficPolicy is not working with exposing bolt as external Loadbalancer.". If you can elaborate in detailed steps with what you executed , which version of helm chart you are using , and what are you expecting 

Thanks,
Harshit

**Comment by harshitsinghvi22** [comment]
Closing this as no response received for the query
