### ISSUE TITLE
Support for StatefulSet annotations

### ISSUE THREAD

**Issue by mattmichal** [neo4j/helm-charts#67]
I'd like to be able to add custom annotations to the StatefulSet that is generated by the neo4j-standalone chart. The chart currently supports labels on the StatefulSet via the `neo4j.labels` config value.

I use cert-manager to generate a TLS certificate which can be mounted via the `ssl.bolt.*` and `ssl.https.*` config values. Initially, this works great. However, when the certificate is renewed, the new cert is not loaded by neo4j until a redeploy is performed. To solve this, I want to use [Reloader](https://github.com/stakater/Reloader) to restart the Pods when the certificate secret changes. However, Reloader requires the addition of an annotation on the StatefulSet which is currently not permitted by the chart.

**Comment by mattmichal** [comment]
@harshitsinghvi22 on #60 you mentioned that support for Pod annotations would be added in 4.4.9. Would it be possible to sneak this feature request into the same release?

**Comment by harshitsinghvi22** [comment]
hey @mattmichal ,

Thanks for raising this issue with us.

Had a chat with my team about this and we all agreed to add this to 4.4.9 release happening this week.

Thanks,
Harshit

**Comment by mattmichal** [comment]
Related PR is #69 .

**Comment by harshitsinghvi22** [comment]
Hi @mattmichal 

4.4.9 is out. 
https://github.com/neo4j/helm-charts/releases/tag/4.4.9

Thanks,
Harshit
