### ISSUE TITLE
Community Edition Headless Version

### ISSUE THREAD

**Issue by mtgnoah** [neo4j/helm-charts#73]
**Is your feature request related to a problem? Please describe.**
I can't use the cluster headless version for community and I need to run a community version for testing. 

**Describe the solution you'd like**
I want to have a headless service for Community

**Describe alternatives you've considered**
I tried this but I still get connect issues from my Python client which is inside a pod. It should connect with uri = "neo4j://192.100.4.100"
```---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: neo4j
    port: 7687
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: neo4j
  namespace: default
subsets:
  - addresses:
      - ip: 192.100.4.100 # your node's IP address
    ports:
      - port: 7687
        name: neo4j
        protocol: TCP```

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by harshitsinghvi22** [comment]
@mtgnoah 
headless service is for clusters only and clusters are an enterprise edition feature only
