### ISSUE TITLE
Make nodeSelector Fully Compatible with Karpenter

### ISSUE THREAD

**Issue by chakatz** [neo4j/helm-charts#93]
**Is your feature request related to a problem? Please describe.**
Neo4j's nodeSelector implementation is not fully compatible with Karpenter.

Karpenter is a Kubernetes node manager with support for AWS EKS. It works with AWS Spot and On-Demand instance types and is quite flexible. https://karpenter.sh/

The way that Neo4j's nodeSelector is currently implemented it looks for node labels on existing nodes and if it finds a match it will request more nodes, but if it does not find a match it will not request a node with those labels.  The result is that if you have defined a Karpenter provisioner but no pods have requested to use it yet, Neo4j with throw an error:
`Error: execution error at (neo4j-standalone/templates/_helpers.tpl:52:16): No node exists in the cluster which has all the below labels (.Values.nodeSelector)`
If Karpenter has already created a node with that provisioner, Neo4j can add a new node, but Neo4j cannot be the first pod to use the provisioner.

**Describe the solution you'd like**
It would be great if the nodeSelector mechanism in Neo4j's Helm chart could request new nodes with the specified labels even if no nodes with those labels currently exist.

**Describe alternatives you've considered**
As a workaround, I created a dummy pod with the labels I wanted which caused Karpenter to create the first node for the provisioner I wanted to use. I then ran the Neo4j chart and Karpenter created a 2nd node using that provisioner. Then I removed the dummy pod.

**Comment by harshitsinghvi22** [comment]
We currently do not support Karpenter @chakatz 
We might look to support it in future but for time being we will not be providing any support

**Comment by AzSiAz** [comment]
I think nodeSelector is broken:
```
failed to create chart from template: execution error at (neo4j-cluster-core/templates/_helpers.tpl:52:16): No node exists in the cluster which has all the below labels (.Values.nodeSelector)
     %smap[k8s.scaleway.com/pool-name:neo4j-dev]
```

No Karpenter, just autoscaler but in my case the nodes are there and will always be but helper function doesn't see them either way

It's a nice addition but I don't think its the job of the helm chart to check this kind of thing at runtime, at least without a way to disable it

**Comment by pchaploutskii** [comment]
Like @AzSiAz mentioned, some is up in "neo4j.checkNodeSelectorLabels" in _helpers.tpl. 
helm lint though an error when nodeSelector has entry:
```
helm lint --debug -f values.yaml
engine.go:180: [INFO] Fail: No node exists in the cluster which has all the below labels (.Values.nodeSelector)
 %smap[agentpool:neo4j-node]
==> Linting .

1 chart(s) linted, 0 chart(s) failed
```

**Comment by lucasarrudatrustly** [comment]
Same problem here, it's the helpers error, it's not about the karpenter.

**Comment by harshitsinghvi22** [comment]
@lucasarrudatrustly  @joywaves 
this can be resolved in 4.4 helm charts by passing the --set disableLookups=true . This flag is released in 4.4.17 helm charts
The change will be release in version 5 too in the next upcoming release

**Comment by lucasarrudatrustly** [comment]
I'm using on 5.4 (must be 5+ for us) I managed to the same effect using affinity, but it's not the best way.
Waiting for the fix I hope that is before production setup 
@harshitsinghvi22 Thank you for the reply

**Comment by harshitsinghvi22** [comment]
closing this as the disableLookups = true was release with version 5 long time ago
