### ISSUE TITLE
[Bug]: Anti-affinity rule interfering with tutorial

### ISSUE THREAD

**Issue by Leander-van-Boven** [neo4j/helm-charts#94]
### Contact Details

l.m.van.boven@student.rug.nl

### What happened?

I tried to follow the [tutorial](https://neo4j.com/docs/operations-manual/current/kubernetes/quickstart-cluster/install-cores/) for running a Neo4J cluster with 3 core instances using the helm charts.

Each time I tried, the first pod was able to start (however stayed in not-ready mode due to only 1 out of 3 required core instances running). The second and third core instances failed to start (stayed in `pending` state) with error `1 node(s) didn't match pod anti-affinity rules`.

Finally I managed to solve this issue by setting `podSpec.podAntiAffinity` to `false` in the `value.yaml` for starting the helm chart. 

As far as I understand the pod anti-affinity rule only allowed one `StatefulSet` instance with the particular `neo4j.name` is was using to be deployed, and any other `StatefulSet` with the same `neo4j.name` would fail.  
However, according to the tutorial, I was meant to run the `helm install` three times with the same `neo4j.name` otherwise they would make three different clusters instead of one with 3 core instances.  
This furthermore raises a question for me why you would deploy three different statefulsets with each 1 pod, as indeed according to the [desired output for `kubectl get pods`](https://neo4j.com/docs/operations-manual/current/kubernetes/quickstart-cluster/verify-cluster-formation/) the `-0` after the pod name indicates the first pod in a certain deployment/statefulset.

Is this indeed intended to have three different statefulsets and then anti-affinity interfering with this intended deployment strategy?

Thanks in advance!

### Chart Name

Cluster

### Chart Version

4.4.1

### Environment

Local Machine

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harshitsinghvi22** [comment]
Hi @Leander-van-Boven , the pod anti affinity rule is set to true to default  to prevent database pods with the same `neo4j.name` running on a single Kubernetes node.
For a cluster you need to have a kubernetes cluster with 3 node or you can set the podAntiAffinity rule to false and deploy all the pods on a single node but that leads to issues if that node goes down or its memory and space limits reaches , hence its better to deploy each of your neo4j instance on a separate node

**Comment by Leander-van-Boven** [comment]
> Hi @Leander-van-Boven , the pod anti affinity rule is set to true to default  to prevent database pods with the same `neo4j.name` running on a single Kubernetes node.
> For a cluster you need to have a kubernetes cluster with 3 node or you can set the podAntiAffinity rule to false and deploy all the pods on a single node but that leads to issues if that node goes down or its memory and space limits reaches , hence its better to deploy each of your neo4j instance on a separate node 
> 
> 

That explains a lot, also why I get this error when running it in my local (one node) minikube cluster. Thanks so much for the fast reply!

**Comment by harshitsinghvi22** [comment]
No problem @Leander-van-Boven . Glad I was able to help.
