### ISSUE TITLE
Missing namespace for ServiceAccount, Role and RoleBinding

### ISSUE THREAD

**Issue by org-ci-cd** [neo4j/helm-charts#95]
Hello guys ! 

I little suggestion here :)

**Is your feature request related to a problem? Please describe.**
When I'm deploying the helm chart using a custom namespace, I expect resources to be created in that namespace

**Describe the solution you'd like**
I would like the SA, Role and RoleBinding in _neo4j-standalone/templates/neo4j-service-account.yaml_ to register in the proper namespace

Does it make sense to you ? 
Thanks !

**Comment by harshitsinghvi22** [comment]
Completed as part of https://github.com/neo4j/helm-charts/pull/109 and https://github.com/neo4j/helm-charts/pull/108
Will be part of the next release
