### ISSUE TITLE
Request: Update Helm Charts for Neo4j v4.4.12

### ISSUE THREAD

**Issue by alexhollis** [neo4j/helm-charts#96]
With Neo4j 4.4.12 being released, it fixes a number of important memory bugs in the application. Can we get the charts updated to 4.4.12 when the team has cycles? 

https://github.com/neo4j/neo4j/releases/tag/4.4.12

Thank!

**Comment by harshitsinghvi22** [comment]
Hi @alexhollis 

4.4.12 is out now
https://github.com/neo4j/helm-charts/releases/tag/4.4.12

Thanks,
Harshit
