### ISSUE TITLE
Support configuring "apoc.jdbc.<alias>.url" from Secret

### ISSUE THREAD

**Issue by johnlinp** [neo4j/helm-charts#98]
**Is your feature request related to a problem? Please describe.**
I have a JDBC connection string that contains username and password. Therefore, I put it in a Kubernetes [Secret](https://kubernetes.io/docs/concepts/configuration/secret/). However, when I'm using the Helm Chart [neo4j-standalone](https://github.com/neo4j/helm-charts/tree/dev/neo4j-standalone), I couldn't find a way to configure the `apoc.jdbc.<alias>.url` to the JDBC connection string in my Secret.

**Describe the solution you'd like**
Currently, there's a `apoc_config` in `values.yaml`. However, it doesn't support referencing values from Secret. If `apoc_config` could support referencing values from Secret, that would solve my problem.

**Describe alternatives you've considered**
I will have to manually modify the Helm Chart and hard-code the Secret.

**Additional context**
None.

**Comment by gem-neo4j** [comment]
Hey! This is now implemented in APOC, and will be released in 5.11 and 4.4.0.20 in the upcoming weeks :)

**Comment by harshitsinghvi22** [comment]
thanks @gem-neo4j

**Comment by johnlinp** [comment]
@gem-neo4j Thank you! May I know the related tickets that fix this issue?

**Comment by harshitsinghvi22** [comment]
Hi @johnlinp ....the fix is not yet pushed for helm charts...once done the ticket will be updated

**Comment by harshitsinghvi22** [comment]
this is implemented now finally and will be part of next release
https://github.com/neo4j/helm-charts/pull/221
https://github.com/neo4j/helm-charts/pull/216

**Comment by johnlinp** [comment]
Thank you @harshitsinghvi22! May I know how I can use this feature? Is it documented anywhere?

**Comment by harshitsinghvi22** [comment]
Hey @johnlinp 

Documentation WL be updated next week at the same time of release.
Keep an eye on the releases section. The next upcoming release shall have all the necessary information.

Thanks
Harshit

**Comment by gem-neo4j** [comment]
For the APOC documentation, it was added [here](https://neo4j.com/docs/apoc/current/config/#config-command-expansion) :)

**Comment by johnlinp** [comment]
Hi @gem-neo4j,

Your link is for "Command Expansion", but I don't see how it's related to configuring Kubernetes Secret. Can you give me some hints? Thank you.

**Comment by harshitsinghvi22** [comment]
@johnlinp this documentation should help
https://neo4j.com/docs/operations-manual/current/kubernetes/plugins/#_configure_credentials_for_plugins_aliases_using_apoc_extended

FYI ... The same thing was mentioned in the releases section too
https://github.com/neo4j/helm-charts/releases/tag/5.11.0

**Comment by johnlinp** [comment]
@harshitsinghvi22 Thank you!
